# Generated by Django 3.1.7 on 2021-05-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210523_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_on',
            new_name='date',
        ),
    ]
